version: 1

formatters:
  precise:
    format: '%(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(request)s - %(message)s'

handlers:
  file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: precise
    filename: /data/homeserver.log
    when: midnight
    backupCount: 7

loggers:
  synapse:
    level: INFO

  synapse.storage.SQL:
    level: WARNING

  synapse.access:
    level: INFO

  synapse.handlers.auth:
    level: INFO

root:
  level: INFO
  handlers: [file]
